import { resolveProofCarryingQaVerdict, type Artifact, type CoverageInput, type DefectSummary, type EvidenceClaim, type EvidenceEvaluation, type Execution, type IndependenceLevel, type Observation, type ProofCarryingObligation, type Producer, type SuccessCriterion, type TraceabilityLink, type VerdictResult } from "../core/qa-core";
export type MaybePromise<T> = T | PromiseLike<T>; export type Clock = () => string | Date;
export const RUN_STATES=["CREATED","BASIS_ESTABLISHED","DISCOVERY_COMPLETED","PLANNED","EXECUTING","EVIDENCE_EVALUATED","VERDICT_RESOLVED","TERMINAL"] as const; export type RunState=(typeof RUN_STATES)[number];
export type CanonicalRunState=Readonly<{schemaVersion:"verification-run/v1";runId:string;requestId:string;rootIdentity:string;snapshotId:string;state:RunState;observationIds:readonly string[];claimIds:readonly string[];evaluationIds:readonly string[];createdAt:string;updatedAt:string}>;
export type BasisKind="request"|"requirement"|"acceptance-criterion"|"defect"|"contract"|"invariant"|"policy"; export type BasisOrigin="explicit"|"derived";
export type VerificationBasisItem=Readonly<{id:string;kind:BasisKind;origin:BasisOrigin;text:string;source?:string}>;
export type VerificationRequest=Readonly<{schemaVersion:"verification-request/v1";requestId:string;project:Readonly<{rootIdentity:string;snapshotId:string}>;change:Readonly<{summary:string;paths:readonly string[]}>;testBasis:readonly VerificationBasisItem[]}>;
export type RiskLevel="R0"|"R1"|"R2"|"R3"; export type VerificationRisk=Readonly<{id:string;level:RiskLevel;impact:number;likelihood:number;basisIds:readonly string[];rationale:string}>;
export type VerificationCondition=Readonly<{id:string;basisIds:readonly string[];riskIds:readonly string[];techniques:readonly string[];expectedResult:string}>;
export type EvidenceType="experiment"|"test-result"|"browser-result"|"build-result"|"static-analysis"|"review"|"approval"|"scenario-result";
export type VerificationObligationPlan=Readonly<{id:string;conditionIds:readonly string[];evidenceType:EvidenceType;mandatory:boolean;independence:IndependenceLevel;entryCriteria:readonly string[];completionCriteria:readonly string[]}>;
export type VerificationPlan=Readonly<{schemaVersion:"verification-plan/v1";requestId:string;snapshotId:string;risks:readonly VerificationRisk[];conditions:readonly VerificationCondition[];obligations:readonly VerificationObligationPlan[]}>;
export type CanonicalVerificationResultArtifact=Readonly<{type:"verification-result";digest:string;path?:string}>;
export type VerificationEvidence=Readonly<{schemaVersion:"verification-evidence/v1";evidenceId:string;requestId:string;snapshotId:string;obligationId:string;producer:Producer;execution:Execution;result:Readonly<{verdict:"PASS"|"FAIL"|"BLOCKED"|"INCOMPLETE";summary:string;passed?:number;failed?:number;artifacts?:readonly string[]}>;observedAt:string;contentHash?:string}>;
export type VerificationExecutionRequest=Readonly<{requestId:string;snapshotId:string;obligation:VerificationObligationPlan;conditionIds:readonly string[]}>;
export type VerificationExecutionOutput=Readonly<{status:"passed"|"failed"|"blocked"|"incomplete"|"PASS"|"FAIL"|"BLOCKED"|"INCOMPLETE";requestId:string;snapshotId:string;producer:Producer;summary?:string;artifacts?:readonly Artifact[];executionKind?:Execution["kind"];identity?:string;exitCode?:number}>;
export type BrowserExecutionRequest=VerificationExecutionRequest; export type BrowserExecutionOutput=VerificationExecutionOutput; export type StoredArtifact=CanonicalVerificationResultArtifact; export type ApprovalRequest=Readonly<{runId:string;defect:DefectSummary}>; export type ApprovalResult=Readonly<{approved:boolean;acceptanceExpiresAt?:string}>; export type UsageEvent=Readonly<{runId:string;obligationId?:string;event:"execution"|"artifact"|"approval"}>;
export type StageName="request"|"basis"|"discovery"|"plan"|"execution"|"evidence"|"residual-risk"|"verdict";
export interface VerificationExecutor {readonly executeObligation?:(i:VerificationExecutionRequest)=>MaybePromise<VerificationExecutionOutput|undefined>;readonly execute?:(i:VerificationExecutionRequest)=>MaybePromise<VerificationExecutionOutput|undefined>};
export interface ArtifactStore {readonly storeVerificationResultArtifact?:(a:CanonicalVerificationResultArtifact,i:VerificationExecutionRequest)=>MaybePromise<CanonicalVerificationResultArtifact|void>;readonly storeArtifact?:(a:Artifact,i:VerificationExecutionRequest)=>MaybePromise<Artifact|void>;readonly putArtifact?:(a:Artifact,i:VerificationExecutionRequest)=>MaybePromise<Artifact|void>;readonly store?:(a:Artifact,i:VerificationExecutionRequest)=>MaybePromise<Artifact|void>};
export interface CapabilityProvider {readonly hasCapability?:(s:string)=>MaybePromise<boolean>;readonly has?:(s:string)=>MaybePromise<boolean>;readonly getCapabilities?:()=>MaybePromise<readonly string[]>;readonly capabilities?:readonly string[]};
export interface BrowserExecutor {readonly executeBrowser?:(i:BrowserExecutionRequest)=>MaybePromise<BrowserExecutionOutput|undefined>;readonly execute?:(i:BrowserExecutionRequest)=>MaybePromise<BrowserExecutionOutput|undefined>};
export interface ApprovalProvider {readonly requestApproval?:(i:ApprovalRequest)=>MaybePromise<ApprovalResult|undefined>;readonly approve?:(i:ApprovalRequest)=>MaybePromise<ApprovalResult|undefined>};
export interface UsageRecorder {readonly recordUsage?:(e:UsageEvent)=>MaybePromise<void>;readonly record?:(e:UsageEvent)=>MaybePromise<void>};
export interface RepositoryPort {readonly loadRun?:(id:string)=>MaybePromise<CanonicalRunState|undefined>;readonly saveRun?:(r:CanonicalRunState)=>MaybePromise<void>;readonly loadStageDocument?:(id:string,s:StageName)=>MaybePromise<unknown|undefined>;readonly saveStageDocument?:(id:string,s:StageName,d:unknown)=>MaybePromise<void>;readonly load?:(id:string)=>MaybePromise<CanonicalRunState|undefined>;readonly save?:(r:CanonicalRunState)=>MaybePromise<void>;readonly loadStage?:(id:string,s:StageName)=>MaybePromise<unknown|undefined>;readonly saveStage?:(id:string,s:StageName,d:unknown)=>MaybePromise<void>}
export type VerificationRunDependencies=Readonly<{repository:RepositoryPort;executor:VerificationExecutor;artifactStore:ArtifactStore;capabilityProvider:CapabilityProvider;browserExecutor?:BrowserExecutor;approvalProvider?:ApprovalProvider;usageRecorder?:UsageRecorder;now:Clock}>;
export type BasisDocument=Readonly<{schemaVersion:"verification-basis/v1";requestId:string;snapshotId:string;basis:readonly VerificationBasisItem[];basisIds:readonly string[]}>; export type DiscoveryDocument=Readonly<{schemaVersion:"risk-discovery/v1";requestId:string;snapshotId:string;risks:readonly VerificationRisk[];conditions:readonly VerificationCondition[]}>; export type PlanDocument=VerificationPlan; export type ExecutionDocument=Readonly<{schemaVersion:"verification-execution/v1";requestId:string;snapshotId:string;observations:readonly Observation[];claims:readonly EvidenceClaim[];evidence:readonly VerificationEvidence[]}>; export type EvidenceDocument=Readonly<{schemaVersion:"verification-evidence-evaluation/v1";requestId:string;snapshotId:string;evaluations:readonly EvidenceEvaluation[];acceptedClaimIds:readonly string[];coverage:CoverageInput}>; export type ResidualRiskDocument=Readonly<{schemaVersion:"verification-residual-risk/v1";requestId:string;snapshotId:string;defects:readonly DefectSummary[]}>; export type VerdictDocument=Readonly<{schemaVersion:"qa-verdict/v1";verdict:VerdictResult}>; export type StageDocument=VerificationRequest|BasisDocument|DiscoveryDocument|PlanDocument|ExecutionDocument|EvidenceDocument|ResidualRiskDocument|VerdictDocument;
export type VerificationRunDocuments={request?:VerificationRequest;basis?:BasisDocument;discovery?:DiscoveryDocument;plan?:PlanDocument;execution?:ExecutionDocument;evidence?:EvidenceDocument;"residual-risk"?:ResidualRiskDocument;verdict?:VerdictDocument};
export type EstablishTestBasisInput=Readonly<{runId?:string;request:VerificationRequest;dependencies:VerificationRunDependencies}>; export type PerformRiskDiscoveryInput=Readonly<{request:VerificationRequest;basis:BasisDocument;dependencies:VerificationRunDependencies}>; export type BuildVerificationPlanInput=Readonly<{request:VerificationRequest;basis:BasisDocument;discovery:DiscoveryDocument;dependencies:VerificationRunDependencies}>; export type ExecuteObligationsInput=Readonly<{runId:string;request:VerificationRequest;plan:VerificationPlan;dependencies:VerificationRunDependencies}>; export type EvaluateEvidenceInput=Readonly<{request:VerificationRequest;plan:VerificationPlan;execution:ExecutionDocument;dependencies:VerificationRunDependencies}>; export type EvaluateResidualRiskInput=Readonly<{runId:string;request:VerificationRequest;plan:VerificationPlan;execution:ExecutionDocument;evidence:EvidenceDocument;dependencies:VerificationRunDependencies}>; export type ResolveVerdictInput=Readonly<{runId:string;request:VerificationRequest;basis:BasisDocument;discovery:DiscoveryDocument;plan:VerificationPlan;execution:ExecutionDocument;evidence:EvidenceDocument;residualRisk:ResidualRiskDocument;dependencies:VerificationRunDependencies}>; export type RunVerificationInput=Readonly<{runId:string;request?:VerificationRequest;dependencies:VerificationRunDependencies}>; export type RunVerificationResult=Readonly<{run:CanonicalRunState;verdict:VerdictResult;documents:VerificationRunDocuments}>;

const DIGEST = /^[0-9a-fA-F]{64}$/;
const uniq = (xs: readonly string[]): string[] => [...new Set(xs)].sort();
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null;
const validDate = (value: unknown): value is string => typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(value) && !Number.isNaN(Date.parse(value));
function validProducer(value: unknown): value is Producer {
  return isRecord(value) && ["self", "harness-managed", "deterministic-verifier", "ci", "human", "external-system"].includes(value.kind as string) && typeof value.identity === "string" && Boolean(value.identity) && ["self-check", "separate-verification-context", "independent-producer", "external-approval"].includes(value.independence as string);
}
function validArtifact(value: unknown): value is CanonicalVerificationResultArtifact {
  return isRecord(value) && value.type === "verification-result" && typeof value.digest === "string" && DIGEST.test(value.digest);
}
function freeze<T>(value: T): T {
  if (value && typeof value === "object" && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value as Record<string, unknown>)) freeze(child);
  }
  return value;
}
function clockNow(clock: Clock): string {
  const value = clock();
  const result = value instanceof Date ? value.toISOString() : value;
  if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(result) || Number.isNaN(Date.parse(result))) throw new Error("clock must return canonical ISO date-time");
  return result;
}
function validRequest(request: VerificationRequest): void {
  if (!isRecord(request) || request.schemaVersion !== "verification-request/v1" || typeof request.requestId !== "string" || !request.requestId || !isRecord(request.project) || typeof request.project.rootIdentity !== "string" || !request.project.rootIdentity || typeof request.project.snapshotId !== "string" || !request.project.snapshotId || !isRecord(request.change) || typeof request.change.summary !== "string" || !Array.isArray(request.change.paths) || request.change.paths.some(path => typeof path !== "string" || !path) || !Array.isArray(request.testBasis)) throw new Error("invalid verification request");
}
export function createInitialRun(runId: string, request: VerificationRequest, now: string): CanonicalRunState {
  validRequest(request);
  if (!runId || !validDate(now)) throw new Error("runId and now are required");
  return freeze({ schemaVersion: "verification-run/v1" as const, runId, requestId: request.requestId, rootIdentity: request.project.rootIdentity, snapshotId: request.project.snapshotId, state: "CREATED" as const, observationIds: [], claimIds: [], evaluationIds: [], createdAt: now, updatedAt: now });
}
export function transitionRunState(run: CanonicalRunState, nextState: RunState, updatedAt: string): CanonicalRunState {
  const current = RUN_STATES.indexOf(run.state);
  const next = RUN_STATES.indexOf(nextState);
  if (current < 0 || next !== current + 1) throw new Error(`invalid run transition ${run.state} -> ${nextState}`);
  if (!validDate(updatedAt)) throw new Error("updatedAt must be canonical ISO date-time");
  return freeze({ ...run, state: nextState, updatedAt });
}
export const transitionRun = transitionRunState;
function criteriaFor(plan: VerificationPlan): readonly SuccessCriterion[] {
  return plan.obligations.map(item => ({ schemaVersion: "success-criterion/v1" as const, criterionId: `criterion:${item.id}`, kind: "structured-assertion" as const, expected: { assertions: [{ field: "execution.exitStatus", operator: "equals" as const, value: "passed" }] }, requiredScope: { kind: "repository-canonical" as const, selectors: [plan.requestId] }, requiredIndependence: item.independence, requiredArtifacts: ["verification-result"] }));
}
function proofObligations(plan: VerificationPlan): readonly ProofCarryingObligation[] {
  return plan.obligations.map(item => ({ id: item.id, mandatory: item.mandatory, criterionIds: [`criterion:${item.id}`], requiredIndependence: item.independence }));
}
function traceLinks(plan: VerificationPlan, discovery: DiscoveryDocument): readonly TraceabilityLink[] {
  const byId = new Map(discovery.conditions.map(item => [item.id, item]));
  return plan.obligations.map(item => {
    const conditionIds = uniq(item.conditionIds);
    return { schemaVersion: "traceability-link/v1" as const, criterionId: `criterion:${item.id}`, conditionIds, basisIds: uniq(conditionIds.flatMap(id => byId.get(id)?.basisIds ?? [])), riskIds: uniq(conditionIds.flatMap(id => byId.get(id)?.riskIds ?? [])) };
  });
}
export async function establishTestBasis(input: EstablishTestBasisInput): Promise<BasisDocument> {
  validRequest(input.request);
  const basis = [...input.request.testBasis].map(item => ({ ...item })).sort((a, b) => a.id.localeCompare(b.id));
  const ids = basis.map(item => item.id);
  if (!ids.length || ids.some(id => !id) || new Set(ids).size !== ids.length) throw new Error("test basis must contain unique IDs");
  return freeze({ schemaVersion: "verification-basis/v1", requestId: input.request.requestId, snapshotId: input.request.project.snapshotId, basis, basisIds: uniq(ids) });
}
function material(item: VerificationBasisItem): string { return `${item.id} ${item.kind} ${item.text} ${item.source ?? ""}`.toLowerCase(); }
function riskLevel(item: VerificationBasisItem): RiskLevel { const text = material(item); if (item.origin === "explicit" && /release|security|migration|persistence|persist|deployment|deploy/.test(text)) return "R3"; if (["contract", "invariant", "defect", "policy"].includes(item.kind)) return "R2"; return "R1"; }
function browserBasis(item: VerificationBasisItem): boolean { return /browser|web|ui|visual|flow/.test(material(item)); }
export async function performRiskDiscovery(input: PerformRiskDiscoveryInput): Promise<DiscoveryDocument> {
  validRequest(input.request);
  const risks = input.basis.basis.map(item => { const level = riskLevel(item); const score = level === "R3" ? 3 : level === "R2" ? 2 : 1; return { id: `risk:${item.id}`, level, impact: score, likelihood: score, basisIds: [item.id], rationale: `Verification risk derived from ${level} basis ${item.id}.` }; }).sort((a, b) => a.id.localeCompare(b.id));
  const conditions = input.basis.basis.map(item => { const techniques = browserBasis(item) ? ["browser-verification", "canonical-verification"] : ["canonical-verification"]; if (riskLevel(item) === "R3") techniques.push("independent-producer"); return { id: `condition:${item.id}`, basisIds: [item.id], riskIds: [`risk:${item.id}`], techniques: uniq(techniques), expectedResult: `Evidence demonstrates ${item.id}.` }; }).sort((a, b) => a.id.localeCompare(b.id));
  return freeze({ schemaVersion: "risk-discovery/v1", requestId: input.request.requestId, snapshotId: input.request.project.snapshotId, risks, conditions });
}
export async function buildVerificationPlan(input: BuildVerificationPlanInput): Promise<PlanDocument> {
  validRequest(input.request);
  const obligations = input.discovery.conditions.map(item => { const levels = item.riskIds.map(id => input.discovery.risks.find(risk => risk.id === id)?.level); const high = levels.includes("R3"); return { id: `obligation:${item.id}`, conditionIds: [item.id], evidenceType: item.techniques.includes("browser-verification") ? "browser-result" as const : "test-result" as const, mandatory: true, independence: high ? "independent-producer" as const : "separate-verification-context" as const, entryCriteria: [], completionCriteria: [item.expectedResult] }; }).sort((a, b) => a.id.localeCompare(b.id));
  return freeze({ schemaVersion: "verification-plan/v1", requestId: input.request.requestId, snapshotId: input.request.project.snapshotId, risks: [...input.discovery.risks].sort((a, b) => a.id.localeCompare(b.id)), conditions: [...input.discovery.conditions].sort((a, b) => a.id.localeCompare(b.id)), obligations });
}
function capabilityFor(obligation: VerificationObligationPlan): string { return obligation.evidenceType === "browser-result" ? "browser" : obligation.evidenceType; }
async function hasCapability(provider: CapabilityProvider, name: string): Promise<boolean> {
  if (provider.hasCapability) return Boolean(await provider.hasCapability(name));
  if (provider.has) return Boolean(await provider.has(name));
  const capabilities = provider.getCapabilities ? await provider.getCapabilities() : provider.capabilities;
  return Boolean(capabilities?.includes(name));
}
async function record(provider: UsageRecorder | undefined, event: UsageEvent): Promise<void> { if (provider?.recordUsage) await provider.recordUsage(event); else if (provider?.record) await provider.record(event); }
async function executeExecutor(port: VerificationExecutor, input: VerificationExecutionRequest): Promise<VerificationExecutionOutput | undefined> { if (port.executeObligation) return port.executeObligation(input); return port.execute ? port.execute(input) : undefined; }
async function executeBrowser(port: BrowserExecutor, input: BrowserExecutionRequest): Promise<BrowserExecutionOutput | undefined> { if (port.executeBrowser) return port.executeBrowser(input); return port.execute ? port.execute(input) : undefined; }
function normalizeStatus(value: VerificationExecutionOutput["status"]): VerificationEvidence["result"]["verdict"] { const status = String(value).toLowerCase(); return status === "passed" || status === "pass" ? "PASS" : status === "failed" || status === "fail" ? "FAIL" : status === "blocked" || status === "block" ? "BLOCKED" : "INCOMPLETE"; }
const INVALID_PRODUCER: Producer = { kind: "self", identity: "", independence: "self-check" };
function producerFor(output: VerificationExecutionOutput | undefined): Producer { return output && validProducer(output.producer) ? output.producer : INVALID_PRODUCER; }
function executionFor(obligation: VerificationObligationPlan, verdict: VerificationEvidence["result"]["verdict"], now: string, output: VerificationExecutionOutput | undefined, producer: Producer): Execution { const exitStatus: Execution["exitStatus"] = verdict === "PASS" ? "passed" : verdict === "FAIL" ? "failed" : verdict === "BLOCKED" ? "blocked" : "cancelled"; return { kind: output?.executionKind ?? (obligation.evidenceType === "browser-result" ? "browser" : "command"), identity: output?.identity ?? producer.identity, startedAt: now, finishedAt: now, exitStatus, ...(output?.exitCode === undefined ? {} : { exitCode: output.exitCode }) }; }
async function storeArtifact(store: ArtifactStore, artifact: CanonicalVerificationResultArtifact, input: VerificationExecutionRequest): Promise<CanonicalVerificationResultArtifact | undefined> { const saved = store.storeVerificationResultArtifact ? await store.storeVerificationResultArtifact(artifact, input) : store.storeArtifact ? await store.storeArtifact(artifact, input) : store.putArtifact ? await store.putArtifact(artifact, input) : store.store ? await store.store(artifact, input) : undefined; return saved && validArtifact(saved) && saved.digest === artifact.digest ? saved : undefined; }
export async function executeObligations(input: ExecuteObligationsInput): Promise<ExecutionDocument> {
  validRequest(input.request); const observedAt = clockNow(input.dependencies.now); const observations: Observation[] = []; const claims: EvidenceClaim[] = []; const evidence: VerificationEvidence[] = [];
  for (const obligation of [...input.plan.obligations].sort((a, b) => a.id.localeCompare(b.id))) {
    const request = { requestId: input.request.requestId, snapshotId: input.request.project.snapshotId, obligation, conditionIds: uniq(obligation.conditionIds) };
    const available = await hasCapability(input.dependencies.capabilityProvider, capabilityFor(obligation));
    const output = available ? obligation.evidenceType === "browser-result" ? input.dependencies.browserExecutor ? await executeBrowser(input.dependencies.browserExecutor, request) : undefined : await executeExecutor(input.dependencies.executor, request) : undefined;
    const verdict = !available ? "BLOCKED" : !output ? "INCOMPLETE" : normalizeStatus(output.status); const summary = !available ? `Capability ${capabilityFor(obligation)} is unavailable.` : !output ? "No executor output was returned." : output.summary ?? `Obligation ${obligation.id} completed.`; const producer = producerFor(output); const artifacts: CanonicalVerificationResultArtifact[] = [];
    if (verdict === "PASS" || verdict === "FAIL") { const supplied = output?.artifacts; const canonical = Array.isArray(supplied) ? supplied.filter(item => item?.type === "verification-result") : []; for (const artifact of canonical) { if (!validArtifact(artifact)) continue; const stored = await storeArtifact(input.dependencies.artifactStore, artifact, request); if (stored) { artifacts.push(stored); await record(input.dependencies.usageRecorder, { runId: input.runId, obligationId: obligation.id, event: "artifact" }); } } }
    const execution = executionFor(obligation, verdict, observedAt, output, producer); const observationId = `observation:${obligation.id}`; const observationRequestId = output?.requestId ?? ""; const observationSnapshotId = output?.snapshotId ?? "";
    observations.push({ schemaVersion: "observation/v1", observationId, requestId: observationRequestId, snapshotId: observationSnapshotId, producer, execution, artifacts });
    evidence.push({ schemaVersion: "verification-evidence/v1", evidenceId: `evidence:${obligation.id}`, requestId: observationRequestId, snapshotId: observationSnapshotId, obligationId: obligation.id, producer, execution, result: { verdict, summary, ...(verdict === "PASS" ? { passed: 1 } : verdict === "FAIL" ? { failed: 1 } : {}), artifacts: artifacts.map(item => item.digest) }, observedAt });
    claims.push({ schemaVersion: "evidence-claim/v1", claimId: `claim:${obligation.id}`, requestId: input.request.requestId, snapshotId: input.request.project.snapshotId, obligationId: obligation.id, criterionId: `criterion:${obligation.id}`, observationIds: [observationId], claim: summary }); await record(input.dependencies.usageRecorder, { runId: input.runId, obligationId: obligation.id, event: "execution" });
  }
  return freeze({ schemaVersion: "verification-execution/v1", requestId: input.request.requestId, snapshotId: input.request.project.snapshotId, observations, claims, evidence });
}
const independenceRank: Readonly<Record<IndependenceLevel, number>> = {"self-check":0,"separate-verification-context":1,"independent-producer":2,"external-approval":3};
function rejectionReasons(checks: EvidenceEvaluation["checks"]): EvidenceEvaluation["rejectionReasons"][number][] { const reasons: EvidenceEvaluation["rejectionReasons"][number][]=[]; if (!checks.snapshotBound) reasons.push("SNAPSHOT_MISMATCH"); if (!checks.fresh) reasons.push("STALE_EVIDENCE"); if (!checks.artifactRequirementsSatisfied) reasons.push("MISSING_ARTIFACT"); if (!checks.scopeComplete) reasons.push("INSUFFICIENT_SCOPE"); if (!checks.producerAllowed) reasons.push("UNTRUSTED_PRODUCER"); if (!checks.independenceSatisfied) reasons.push("INDEPENDENCE_NOT_MET"); if (!checks.expectedResultDemonstrated || checks.expectedResultViolated) reasons.push("EXPECTED_RESULT_NOT_DEMONSTRATED"); if (!checks.integrityVerified) reasons.push("INTEGRITY_FAILURE"); return uniq(reasons) as EvidenceEvaluation["rejectionReasons"][number][]; }
function makeEvaluation(observation: Observation | undefined, claim: EvidenceClaim, obligation: VerificationObligationPlan, evaluatedAt: string, request: VerificationRequest): EvidenceEvaluation {
  const producerValid = Boolean(observation && validProducer(observation.producer)); const producerAllowed = producerValid && !(observation?.producer.kind === "self" && observation.producer.independence !== "self-check"); const snapshotBound = Boolean(observation && claim.requestId === request.requestId && claim.snapshotId === request.project.snapshotId && observation.requestId === request.requestId && observation.snapshotId === request.project.snapshotId); const scopeComplete = Boolean(observation && claim.obligationId === obligation.id && claim.criterionId === `criterion:${obligation.id}` && claim.observationIds.length > 0); const artifactRequirementsSatisfied = Boolean(observation?.artifacts.some(item => validArtifact(item))); const expectedResultDemonstrated = observation?.execution.exitStatus === "passed"; const expectedResultViolated = observation?.execution.exitStatus === "failed"; const independenceSatisfied = Boolean(observation && independenceRank[observation.producer.independence] >= independenceRank[obligation.independence]); const integrityVerified = Boolean(observation && producerValid && snapshotBound && observation.artifacts.every(item => validArtifact(item))); const checks = { snapshotBound, fresh:true, scopeComplete, producerAllowed, independenceSatisfied, artifactRequirementsSatisfied, expectedResultDemonstrated, expectedResultViolated, integrityVerified }; const reasons = rejectionReasons(checks);
  return { schemaVersion:"evidence-evaluation/v1", evaluationId:`evaluation:${claim.claimId}`, requestId:claim.requestId, snapshotId:claim.snapshotId, claimId:claim.claimId, status:reasons.length === 0 ? "ACCEPTED" : "REJECTED", checks, rejectionReasons:reasons, evaluatedAt };
}
export async function evaluateEvidence(input: EvaluateEvidenceInput): Promise<EvidenceDocument> {
  validRequest(input.request); const evaluatedAt = clockNow(input.dependencies.now); const observations = new Map(input.execution.observations.map(item => [item.observationId, item])); const evaluations = [...input.execution.claims].sort((a,b)=>a.claimId.localeCompare(b.claimId)).map(claim => makeEvaluation(observations.get(claim.observationIds[0]), claim, input.plan.obligations.find(item=>item.id===claim.obligationId) ?? input.plan.obligations[0], evaluatedAt, input.request)); const claimsById = new Map(input.execution.claims.map(claim => [claim.claimId, claim])); const accepted = new Set(evaluations.filter(item=>item.status==="ACCEPTED").map(item=>claimsById.get(item.claimId)?.obligationId).filter((id):id is string=>Boolean(id))); const conditionById = new Map(input.plan.conditions.map(item=>[item.id,item])); const coveredConditions = uniq(input.plan.obligations.filter(item=>accepted.has(item.id)).flatMap(item=>item.conditionIds));
  return freeze({ schemaVersion:"verification-evidence-evaluation/v1", requestId:input.request.requestId, snapshotId:input.request.project.snapshotId, evaluations, acceptedClaimIds:evaluations.filter(item=>item.status==="ACCEPTED").map(item=>item.claimId).sort(), coverage:{basisIds:uniq(input.plan.conditions.flatMap(item=>item.basisIds)),coveredBasisIds:uniq(coveredConditions.flatMap(id=>conditionById.get(id)?.basisIds ?? [])),riskIds:uniq(input.plan.risks.map(item=>item.id)),coveredRiskIds:uniq(coveredConditions.flatMap(id=>conditionById.get(id)?.riskIds ?? [])),conditionIds:uniq(input.plan.conditions.map(item=>item.id)),coveredConditionIds:coveredConditions} });
}
export async function evaluateResidualRisk(input: EvaluateResidualRiskInput): Promise<ResidualRiskDocument> {
  const claimsById = new Map(input.execution.claims.map(claim => [claim.claimId, claim])); const accepted = new Set(input.evidence.evaluations.filter(item => item.status === "ACCEPTED").map(item => claimsById.get(item.claimId)?.obligationId).filter((id): id is string => Boolean(id))); const defects: DefectSummary[] = [];
  for (const obligation of input.plan.obligations) {
    if (accepted.has(obligation.id)) continue;
    const defect: DefectSummary = { id: `residual:${obligation.id}`, material: obligation.mandatory, disposition: "OPEN" }; const provider = input.dependencies.approvalProvider; const approval = provider?.requestApproval ? await provider.requestApproval({ runId: input.runId, defect }) : provider?.approve ? await provider.approve({ runId: input.runId, defect }) : undefined;
    await record(input.dependencies.usageRecorder, { runId: input.runId, obligationId: obligation.id, event: "approval" }); defects.push(approval?.approved ? { ...defect, disposition: "ACCEPTED_RISK", acceptanceExpiresAt: approval.acceptanceExpiresAt } : defect);
  }
  return freeze({ schemaVersion: "verification-residual-risk/v1", requestId: input.request.requestId, snapshotId: input.request.project.snapshotId, defects });
}
export async function resolveVerdict(input: ResolveVerdictInput): Promise<VerdictDocument> {
  validRequest(input.request);
  const proof = { requestId: input.request.requestId, snapshotId: input.request.project.snapshotId, obligations: proofObligations(input.plan), criteria: criteriaFor(input.plan), observations: input.execution.observations, claims: input.execution.claims, evaluations: input.evidence.evaluations, defects: input.residualRisk.defects, coverage: input.evidence.coverage, evaluatedAt: clockNow(input.dependencies.now), traceability: traceLinks(input.plan, input.discovery) };
  return freeze({ schemaVersion: "qa-verdict/v1", verdict: resolveProofCarryingQaVerdict(proof) });
}
async function loadRun(repository: RepositoryPort, runId: string): Promise<CanonicalRunState | undefined> { const run = repository.loadRun ? await repository.loadRun(runId) : repository.load ? await repository.load(runId) : undefined; if (run && (!isRecord(run) || run.schemaVersion !== "verification-run/v1" || run.runId !== runId || typeof run.requestId !== "string" || !run.requestId || typeof run.rootIdentity !== "string" || !run.rootIdentity || typeof run.snapshotId !== "string" || !run.snapshotId || !RUN_STATES.includes(run.state as RunState) || !validDate(run.createdAt) || !validDate(run.updatedAt) || !Array.isArray(run.observationIds) || !Array.isArray(run.claimIds) || !Array.isArray(run.evaluationIds) || [run.observationIds,run.claimIds,run.evaluationIds].some(ids=>ids.some(id=>typeof id!=="string" || !id || new Set(ids).size !== ids.length)))) throw Error("invalid persisted run"); return run; }
async function saveRun(repository: RepositoryPort, run: CanonicalRunState): Promise<void> { if (repository.saveRun) return repository.saveRun(run); if (repository.save) return repository.save(run); throw Error("repository does not implement saveRun"); }
async function loadStage<T>(repository: RepositoryPort, runId: string, stage: StageName): Promise<T | undefined> { if (repository.loadStageDocument) return repository.loadStageDocument(runId, stage) as MaybePromise<T | undefined>; if (repository.loadStage) return repository.loadStage(runId, stage) as MaybePromise<T | undefined>; throw Error("repository does not implement loadStageDocument"); }
async function saveStage(repository: RepositoryPort, runId: string, stage: StageName, document: StageDocument): Promise<void> { if (repository.saveStageDocument) return repository.saveStageDocument(runId, stage, document); if (repository.saveStage) return repository.saveStage(runId, stage, document); throw Error("repository does not implement saveStageDocument"); }
function validateStage(stage: StageName, value: unknown, request: VerificationRequest, prior?: VerificationRunDocuments): void {
  if (stage === "request") { validRequest(value as VerificationRequest); return; }
  if (!isRecord(value) || value.requestId !== request.requestId || value.snapshotId !== request.project.snapshotId) throw Error(`invalid persisted ${stage} stage`);
  const schema: Record<Exclude<StageName, "request">, string> = { basis:"verification-basis/v1", discovery:"risk-discovery/v1", plan:"verification-plan/v1", execution:"verification-execution/v1", evidence:"verification-evidence-evaluation/v1", "residual-risk":"verification-residual-risk/v1", verdict:"qa-verdict/v1" };
  if (stage === "verdict") { if (!isRecord(value.verdict) || value.verdict.schemaVersion !== "qa-verdict/v1" || value.verdict.requestId !== request.requestId || value.verdict.snapshotId !== request.project.snapshotId) throw Error("invalid persisted verdict stage"); return; }
  if (value.schemaVersion !== schema[stage]) throw Error(`invalid persisted ${stage} stage`);
  if (stage === "basis") {
    if (!Array.isArray(value.basis) || !Array.isArray(value.basisIds) || value.basis.some(item=>!isRecord(item) || typeof item.id !== "string" || !item.id) || value.basisIds.some(id=>typeof id!=="string") || JSON.stringify(value.basisIds) !== JSON.stringify(uniq((value.basis as VerificationBasisItem[]).map(item=>item.id)))) throw Error("invalid persisted basis stage");
  } else if (stage === "discovery") {
    if (!Array.isArray(value.risks) || !Array.isArray(value.conditions)) throw Error("invalid persisted discovery stage");
    const riskIds = value.risks.map(risk=>isRecord(risk) ? risk.id : ""); if (riskIds.some(id=>typeof id!=="string" || !id) || new Set(riskIds).size !== riskIds.length) throw Error("invalid persisted discovery stage");
    const riskSet = new Set(riskIds); const basisSet = prior?.basis ? new Set(prior.basis.basisIds) : undefined; const conditionIds = value.conditions.map(condition=>isRecord(condition) ? condition.id : ""); if (conditionIds.some(id=>typeof id!=="string" || !id) || new Set(conditionIds).size !== conditionIds.length) throw Error("invalid persisted discovery stage");
    for (const risk of value.risks) if (!isRecord(risk) || !Array.isArray(risk.basisIds) || risk.basisIds.some(id=>typeof id!=="string" || (basisSet && !basisSet.has(id))) ) throw Error("invalid persisted discovery reference");
    for (const condition of value.conditions) if (!isRecord(condition) || !Array.isArray(condition.basisIds) || condition.basisIds.some(id=>typeof id!=="string" || (basisSet && !basisSet.has(id))) || !Array.isArray(condition.riskIds) || condition.riskIds.some(id=>!riskSet.has(id as string))) throw Error("invalid persisted discovery reference");
  } else if (stage === "plan") {
    if (!Array.isArray(value.risks) || !Array.isArray(value.conditions) || !Array.isArray(value.obligations)) throw Error("invalid persisted plan stage");
    const priorConditionSet = prior?.discovery ? new Set(prior.discovery.conditions.map(item=>item.id)) : undefined; const priorRiskSet = prior?.discovery ? new Set(prior.discovery.risks.map(item=>item.id)) : undefined; const conditionSet = new Set(value.conditions.map(condition=>isRecord(condition) ? condition.id : "")); const obligationIds = value.obligations.map(obligation=>isRecord(obligation) ? obligation.id : ""); if (obligationIds.some(id=>typeof id!=="string" || !id) || new Set(obligationIds).size !== obligationIds.length) throw Error("invalid persisted plan stage");
    if (value.conditions.some(condition=>!isRecord(condition) || (priorConditionSet && !priorConditionSet.has(condition.id as string))) || value.risks.some(risk=>!isRecord(risk) || (priorRiskSet && !priorRiskSet.has(risk.id as string)))) throw Error("invalid persisted plan reference");
    for (const obligation of value.obligations) if (!isRecord(obligation) || !Array.isArray(obligation.conditionIds) || obligation.conditionIds.some(id=>!conditionSet.has(id as string)) || !["experiment","test-result","browser-result","build-result","static-analysis","review","approval","scenario-result"].includes(obligation.evidenceType as string)) throw Error("invalid persisted plan reference");
  } else if (stage === "execution") {
    if (!Array.isArray(value.observations) || !Array.isArray(value.claims) || !Array.isArray(value.evidence)) throw Error("invalid persisted execution stage");
    const observationIds = value.observations.map(observation=>isRecord(observation) ? observation.observationId : ""); if (observationIds.some(id=>typeof id!=="string" || !id) || new Set(observationIds).size !== observationIds.length) throw Error("invalid persisted execution stage");
    const observationSet = new Set(observationIds); const claimIds = value.claims.map(claim=>isRecord(claim) ? claim.claimId : ""); if (claimIds.some(id=>typeof id!=="string" || !id) || new Set(claimIds).size !== claimIds.length) throw Error("invalid persisted execution stage");
    const obligationSet = prior?.plan ? new Set(prior.plan.obligations.map(item=>item.id)) : undefined;
    for (const observation of value.observations) if (!isRecord(observation) || observation.schemaVersion !== "observation/v1" || observation.requestId !== request.requestId || observation.snapshotId !== request.project.snapshotId || !validProducer(observation.producer) || typeof observation.requestId !== "string" || typeof observation.snapshotId !== "string" || !isRecord(observation.execution) || !Array.isArray(observation.artifacts) || observation.artifacts.some(artifact=>!validArtifact(artifact))) throw Error("invalid persisted execution reference");
    for (const claim of value.claims) if (!isRecord(claim) || claim.requestId !== request.requestId || claim.snapshotId !== request.project.snapshotId || !Array.isArray(claim.observationIds) || claim.observationIds.some(id=>!observationSet.has(id as string)) || typeof claim.obligationId !== "string" || !claim.obligationId || typeof claim.criterionId !== "string" || claim.criterionId !== `criterion:${claim.obligationId}` || (obligationSet && !obligationSet.has(claim.obligationId))) throw Error("invalid persisted claim reference");
    for (const item of value.evidence) if (!isRecord(item) || item.schemaVersion !== "verification-evidence/v1" || item.requestId !== request.requestId || item.snapshotId !== request.project.snapshotId || typeof item.obligationId !== "string" || (obligationSet && !obligationSet.has(item.obligationId)) || !validProducer(item.producer) || !isRecord(item.execution) || !isRecord(item.result)) throw Error("invalid persisted execution evidence reference");
  } else if (stage === "evidence") {
    if (!Array.isArray(value.evaluations) || !Array.isArray(value.acceptedClaimIds) || !isRecord(value.coverage)) throw Error("invalid persisted evidence stage");
    const coverage = value.coverage as Record<string, unknown>; const evaluationIds = value.evaluations.map(evaluation=>isRecord(evaluation) ? evaluation.evaluationId : ""); if (evaluationIds.some(id=>typeof id!=="string" || !id) || new Set(evaluationIds).size !== evaluationIds.length) throw Error("invalid persisted evidence stage");
    const claimSet = prior?.execution ? new Set(prior.execution.claims.map(item=>item.claimId)) : undefined; const evaluationByClaim = new Map(value.evaluations.filter(item=>isRecord(item)).map(item=>[item.claimId, item.status])); if (value.acceptedClaimIds.some(id=>typeof id!=="string" || (claimSet && !claimSet.has(id as string)) || evaluationByClaim.get(id as string) === "REJECTED") || new Set(value.acceptedClaimIds).size !== value.acceptedClaimIds.length || !["basisIds","coveredBasisIds","riskIds","coveredRiskIds","conditionIds","coveredConditionIds"].every(key=>Array.isArray(coverage[key]) && (coverage[key] as unknown[]).every(id=>typeof id==="string"))) throw Error("invalid persisted evidence coverage");
    for (const evaluation of value.evaluations) { if (!isRecord(evaluation) || evaluation.schemaVersion !== "evidence-evaluation/v1" || evaluation.requestId !== request.requestId || evaluation.snapshotId !== request.project.snapshotId || typeof evaluation.claimId !== "string" || (claimSet && !claimSet.has(evaluation.claimId)) || !isRecord(evaluation.checks)) throw Error("invalid persisted evidence reference"); const checks = evaluation.checks as Record<string, unknown>; if (!["snapshotBound","fresh","scopeComplete","producerAllowed","independenceSatisfied","artifactRequirementsSatisfied","expectedResultDemonstrated","expectedResultViolated","integrityVerified"].every(key=>typeof checks[key]==="boolean")) throw Error("invalid persisted evidence reference"); }
  } else if (stage === "residual-risk" && (!Array.isArray(value.defects) || value.defects.some(defect=>!isRecord(defect) || typeof defect.id!=="string" || !defect.id))) throw Error("invalid persisted residual-risk stage");
}
async function loadCheckedStage<T>(repository: RepositoryPort, runId: string, stage: StageName, request: VerificationRequest, prior?: VerificationRunDocuments): Promise<T | undefined> { const value = await loadStage<T>(repository, runId, stage); if (value !== undefined) validateStage(stage, value, request, prior); return value; }
export async function runVerification(input: RunVerificationInput): Promise<RunVerificationResult> {
  const { dependencies } = input; const repository = dependencies.repository; let run = await loadRun(repository, input.runId); const persisted = await loadStage<VerificationRequest>(repository, input.runId, "request"); if (persisted) validateStage("request", persisted, input.request ?? persisted);
  let request = input.request;
  if (run) {
    if (!persisted) throw Error("resume requires persisted request document");
    if (request && (request.requestId !== persisted.requestId || request.project.rootIdentity !== persisted.project.rootIdentity || request.project.snapshotId !== persisted.project.snapshotId)) throw Error("resume request identity mismatch");
    request = persisted; if (run.runId !== input.runId || run.requestId !== request.requestId || run.rootIdentity !== request.project.rootIdentity || run.snapshotId !== request.project.snapshotId) throw Error("run identity mismatch");
  } else {
    if (!request && !persisted) throw Error("request is required when creating a run"); if (request) validRequest(request); if (persisted && request && (request.requestId !== persisted.requestId || request.project.rootIdentity !== persisted.project.rootIdentity || request.project.snapshotId !== persisted.project.snapshotId)) throw Error("request identity mismatch"); request = persisted ?? request; if (!request) throw Error("request is required when creating a run"); run = createInitialRun(input.runId, request, clockNow(dependencies.now)); if (!persisted) await saveStage(repository, input.runId, "request", request); await saveRun(repository, run);
  }
  validRequest(request); const req = request; const documents: VerificationRunDocuments = { request: persisted ?? req };
  while (run.state !== "TERMINAL") {
    if (run.state === "CREATED") { const doc = await establishTestBasis({ runId: input.runId, request: req, dependencies }); documents.basis = doc; await saveStage(repository, input.runId, "basis", doc); run = transitionRunState(run, "BASIS_ESTABLISHED", clockNow(dependencies.now)); await saveRun(repository, run); continue; }
    const basis = documents.basis ?? await loadCheckedStage<BasisDocument>(repository, input.runId, "basis", req, documents); if (basis) documents.basis = basis;
    if (run.state === "BASIS_ESTABLISHED") { if (!basis) throw Error("basis document is missing"); const doc = await performRiskDiscovery({ request: req, basis, dependencies }); documents.discovery = doc; await saveStage(repository, input.runId, "discovery", doc); run = transitionRunState(run, "DISCOVERY_COMPLETED", clockNow(dependencies.now)); await saveRun(repository, run); continue; }
    const discovery = documents.discovery ?? await loadCheckedStage<DiscoveryDocument>(repository, input.runId, "discovery", req, documents); if (discovery) documents.discovery = discovery;
    if (run.state === "DISCOVERY_COMPLETED") { if (!basis || !discovery) throw Error("basis or discovery document is missing"); const doc = await buildVerificationPlan({ request: req, basis, discovery, dependencies }); documents.plan = doc; await saveStage(repository, input.runId, "plan", doc); run = transitionRunState(run, "PLANNED", clockNow(dependencies.now)); await saveRun(repository, run); continue; }
    const plan = documents.plan ?? await loadCheckedStage<PlanDocument>(repository, input.runId, "plan", req, documents); if (plan) documents.plan = plan;
    if (run.state === "PLANNED") { if (!plan) throw Error("plan document is missing"); const checkpoint = documents.execution ?? await loadCheckedStage<ExecutionDocument>(repository, input.runId, "execution", req, documents); if (checkpoint) { documents.execution = checkpoint; run = transitionRunState({ ...run, observationIds: checkpoint.observations.map(item=>item.observationId), claimIds: checkpoint.claims.map(item=>item.claimId) }, "EXECUTING", clockNow(dependencies.now)); await saveRun(repository, run); continue; } const doc = await executeObligations({ runId: input.runId, request: req, plan, dependencies }); documents.execution = doc; await saveStage(repository, input.runId, "execution", doc); run = transitionRunState({ ...run, observationIds: doc.observations.map(item=>item.observationId), claimIds: doc.claims.map(item=>item.claimId) }, "EXECUTING", clockNow(dependencies.now)); await saveRun(repository, run); continue; }
    const execution = documents.execution ?? await loadCheckedStage<ExecutionDocument>(repository, input.runId, "execution", req, documents); if (execution) documents.execution = execution;
    if (run.state === "EXECUTING") { if (!plan || !execution) throw Error("plan or execution document is missing"); const doc = await evaluateEvidence({ request:req, plan, execution, dependencies }); documents.evidence = doc; await saveStage(repository, input.runId, "evidence", doc); run = transitionRunState({ ...run, evaluationIds: doc.evaluations.map(item=>item.evaluationId) }, "EVIDENCE_EVALUATED", clockNow(dependencies.now)); await saveRun(repository, run); continue; }
    const evidence = documents.evidence ?? await loadCheckedStage<EvidenceDocument>(repository, input.runId, "evidence", req, documents); if (evidence) documents.evidence = evidence;
    if (run.state === "EVIDENCE_EVALUATED") { if (!basis || !discovery || !plan || !execution || !evidence) throw Error("proof documents are missing"); const saved = documents["residual-risk"] ?? await loadCheckedStage<ResidualRiskDocument>(repository, input.runId, "residual-risk", req, documents); const residual = saved ?? await evaluateResidualRisk({ runId:input.runId, request:req, plan, execution, evidence, dependencies }); documents["residual-risk"] = residual; if (!saved) await saveStage(repository, input.runId, "residual-risk", residual); const verdict = await resolveVerdict({ runId:input.runId, request:req, basis, discovery, plan, execution, evidence, residualRisk:residual, dependencies }); documents.verdict = verdict; await saveStage(repository, input.runId, "verdict", verdict); run = transitionRunState(run, "VERDICT_RESOLVED", clockNow(dependencies.now)); await saveRun(repository, run); continue; }
    const verdict = documents.verdict ?? await loadCheckedStage<VerdictDocument>(repository, input.runId, "verdict", req, documents); if (!verdict) throw Error("verdict document is missing"); documents.verdict = verdict; run = transitionRunState(run, "TERMINAL", clockNow(dependencies.now)); await saveRun(repository, run);
  }
  const verdict = documents.verdict ?? await loadCheckedStage<VerdictDocument>(repository, input.runId, "verdict", req, documents); if (!verdict) throw Error("terminal run has no verdict document"); documents.verdict = verdict; return freeze({ run, verdict: verdict.verdict, documents });
}